export interface SubredditPseoTarget {
    slug: string;
    audience: string;
    postingTip: string;
    description: string;
    pitfalls: string[];
    checklist: string[];
}

export const SUBREDDIT_PSEO_TARGETS: SubredditPseoTarget[] = [
    { slug: "AskReddit", audience: "broad discussion seekers", postingTip: "Lead with a clear, open-ended question and avoid promotional links.", description: "r/AskReddit rewards curiosity and discussion starters, not advice threads or self-promotion. The best posts are simple, relatable questions that invite stories.", pitfalls: ["Yes/no questions get removed — phrase as open-ended", "No personal advice or 'what should I do?' without context", "No spam, surveys, or leading questions"], checklist: ["Title is a single question under 300 chars", "No links in title", "Body adds context without answering your own question"] },
    { slug: "Entrepreneur", audience: "founders and operators", postingTip: "Share specific lessons, numbers, and outcomes instead of generic advice.", description: "r/Entrepreneur values battle stories with revenue, timeline, and real constraints. Generic motivation and vague asks without context are quickly removed.", pitfalls: ["No self-promotion or hiring posts without context", "Low-effort 'how do I start?' without research", "No blog spam or affiliate links"], checklist: ["Include niche, traction numbers, and what you already tried", "Remove hype words like 'passive income guaranteed'", "Ask a specific, answerable business question"] },
    { slug: "smallbusiness", audience: "small business owners", postingTip: "Use practical examples and clearly state your business context.", description: "r/smallbusiness expects owner-operator detail: industry, location, employees, and revenue stage. Vague ideas without execution detail don't survive.", pitfalls: ["No market research requests without showing effort", "No repetitive legal/tax questions without jurisdiction", "No self-promo without value first"], checklist: ["State business type, stage, and constraint", "Include numbers: revenue, margin, CAC", "One clear question per post"] },
    { slug: "startups", audience: "startup builders", postingTip: "Focus on traction, experiments, and transparent metrics.", description: "r/startups is for builders sharing experiments and metrics. Pitch decks and stealth-mode teasers without data are removed.", pitfalls: ["No direct funding asks without traction", "No idea validation without landing page or interviews", "No launch spam — share learnings, not ads"], checklist: ["Stack, metrics (MRR, churn, activation), and timeline included", "Explain hypothesis and what you tested", "No external link as the whole post"] },
    { slug: "SaaS", audience: "SaaS operators", postingTip: "Provide actionable takeaways and avoid self-promo wording.", description: "r/SaaS wants teardown-level detail on pricing, churn, and distribution. Success story posts without playbooks get flagged.", pitfalls: ["No shameless plug — 9:1 value rule", "No vague 'we grew to $10k MRR' without how", "No affiliate or LTD spam"], checklist: ["Pricing model, ACV, and churn context present", "Distribution channel explained in detail", "Loom/video demo linked as supplement, not substance"] },
    { slug: "marketing", audience: "marketers", postingTip: "Cite campaign details and remove hype-heavy claims.", description: "r/marketing filters guru content. Provide channel, budget, KPI, and creative — not just 'we went viral'.", pitfalls: ["No self-promotion or service offers", "No low-effort case studies without data", "No engagement bait"], checklist: ["Channel, spend, duration, and KPI defined", "Creative angle and hook explained", "Lesson is reproducible, not lucky"] },
    { slug: "digital_marketing", audience: "digital marketers", postingTip: "Add channel-specific context and realistic performance data.", description: "r/digital_marketing needs platform, targeting, and benchmark context. Screenshots without explanation are often removed.", pitfalls: ["No client solicitation", "No screenshot dumps without narrative", "No unverified 'hack' claims"], checklist: ["Platform, targeting, budget, and objective stated", "Metrics include CTR, CPC, CVR, and baseline", "What you tested next included"] },
    { slug: "socialmedia", audience: "social media practitioners", postingTip: "Keep claims evidence-based and include tactical steps.", description: "r/socialmedia wants platform-specific tactics with posting cadence and content format. Viral theory without proof doesn't rank.", pitfalls: ["No follow-for-follow or engagement pods", "No generic 'be consistent' posts", "No tool spam"], checklist: ["Platform, format (Reels, carousel), and cadence listed", "Results include reach, saves, and conversion", "Tool stack mentioned only if central"] },
    { slug: "webdev", audience: "web developers", postingTip: "Show technical context, constraints, and implementation details.", description: "r/webdev expects stack, browser, and code context. 'Which tech should I learn?' without goal is removed.", pitfalls: ["No low-effort career posts without context", "No image-only showcase without tech detail", "No repost of docs without question"], checklist: ["Stack, hosting, and repo link if relevant", "Code snippet is minimal and reproducible", "Error message and what you tried included"] },
    { slug: "programming", audience: "software engineers", postingTip: "Use precise language and include reproducible examples.", description: "r/programming is for in-depth engineering discussion. Link dumps without summary are removed.", pitfalls: ["No paywalled links without summary", "No memes or low-effort hot takes", "Exact duplications of blog posts"], checklist: ["Problem, constraint, and trade-off stated", "Link post includes 3-bullet TL;DR", "No blog spam — add original insight"] },
    { slug: "learnprogramming", audience: "new developers", postingTip: "Ask focused questions and include what you've already tried.", description: "r/learnprogramming rewards effort shown. 'My code doesn't work' without code is auto-removed.", pitfalls: ["No homework dump without attempt", "No vague 'what language should I learn?'", "No solution requests without code"], checklist: ["Language, error, and snippet included", "Explain expected vs actual behavior", "Format code with markdown code block"] },
    { slug: "reactjs", audience: "React developers", postingTip: "Include version info and concrete code snippets.", description: "r/reactjs needs React version, bundler, and minimal reproduction. Generic 'best practice?' without code is low-effort.", pitfalls: ["No hiring or self-promo", "No screenshots of code", "No low-effort poll without context"], checklist: ["React version, Vite/Next version, and deps listed", "Minimal repro on StackBlitz/CodeSandbox", "State shape and effect deps shown"] },
    { slug: "nextjs", audience: "Next.js developers", postingTip: "Mention routing/runtime details and deployment environment.", description: "r/nextjs expects App Router vs Pages, runtime, and Vercel/hosting detail. Showcase posts without question get removed.", pitfalls: ["No showcase without technical question", "No image-only without stack", "No duplicate docs question without code"], checklist: ["Next version, router type, and runtime (edge/node) listed", "Deployment target (Vercel, self-host) explained", "Config snippet included if relevant"] },
    { slug: "javascript", audience: "JavaScript developers", postingTip: "Share minimal examples and expected vs actual behavior.", description: "r/javascript is strict on original content and formatting. Help posts without attempt are redirected.", pitfalls: ["No 'help me' without code", "No repost of MDN without question", "No job or survey posts"], checklist: ["Runnable snippet with console output", "Browser/Node version noted", "No unrelated framework code"] },
    { slug: "typescript", audience: "TypeScript developers", postingTip: "Include type definitions and compiler errors where relevant.", description: "r/typescript wants type, compiler options, and error text. Opinion polls without code are removed.", pitfalls: ["No low-effort 'TS vs JS' without nuance", "No config dump without error", "No self-promo"], checklist: ["TS version, tsconfig strict flag, and error code included", "Type snippet is minimal", "Expected type vs actual explained"] },
    { slug: "ChatGPT", audience: "AI tool users", postingTip: "Describe prompts, constraints, and intended outputs clearly.", description: "r/ChatGPT filters prompt dumps without context. Share prompt, model, and failure mode.", pitfalls: ["No low-effort prompt lists without use case", "No misinformation or jailbreak instructions", "No karma farming reposts"], checklist: ["Model, prompt, temperature, and output included", "Goal and failure mode described", "Edit includes what you already tried"] },
    { slug: "MachineLearning", audience: "ML practitioners", postingTip: "Provide dataset/model context and avoid broad unverified claims.", description: "r/MachineLearning expects paper-level rigor: dataset size, metric, and ablation. Press-release posts without method are removed.", pitfalls: ["No headline-only link", "No low-effort 'will AI replace X?'", "No resource dumps without review"], checklist: ["Dataset size, split, and metric stated", "Baseline and hyperparams noted", "Paper link includes TL;DR summary"] },
    { slug: "artificial", audience: "AI community", postingTip: "Anchor discussion in concrete use cases and practical tradeoffs.", description: "r/artificial wants applied AI discussion with stack and trade-off. Sci-fi speculation without tech is removed.", pitfalls: ["No sensational 'AGI soon' without source", "No tool spam", "No repost of press release"], checklist: ["Use case, stack, and cost/latency discussed", "Source linked with summary", "Question invites engineering answers"] },
    { slug: "technology", audience: "tech enthusiasts", postingTip: "Keep headlines factual and avoid sensational framing.", description: "r/technology requires editorialized title rule and credible source. Blog spam and misleading titles are removed.", pitfalls: ["No editorialized titles", "No blog spam or self-posted press release", "No duplicate coverage"], checklist: ["Headline matches article verbatim (or flagged)", "Source is credible and linked", "Submission statement if required"] },
    { slug: "productivity", audience: "productivity-focused users", postingTip: "Share before/after workflows and measurable improvements.", description: "r/productivity filters generic advice. Show system, duration used, and measured effect.", pitfalls: ["No affiliate tool spam", "No low-effort 'just wake up at 5am'", "No duplicate 'pomodoro' posts"], checklist: ["System, duration, and frequency stated", "Before/after metric (time saved, tasks done)", "Tool is secondary to method"] },
    { slug: "freelance", audience: "freelancers", postingTip: "Give real client context and realistic constraints.", description: "r/freelance wants rate, niche, and client source detail. Vague 'how to find clients?' without niche is removed.", pitfalls: ["No low-effort client sourcing ask", "No unpaid work offers", "No self-promo without story"], checklist: ["Niche, rate, and outreach volume included", "Client type and acquisition channel named", "One decision question, not open-ended"] },
    { slug: "copywriting", audience: "writers and marketers", postingTip: "Lead with audience intent and avoid spam-like language.", description: "r/copywriting values voice, audience, and before/after copy. Link-only portfolios without teardown are removed.", pitfalls: ["No portfolio dump without teardown", "No AI-spam copy", "No client solicitation"], checklist: ["Audience, offer, and channel stated", "Before/after copy included", "Feedback ask is specific (headline, CTA, etc.)"] },
    { slug: "content_marketing", audience: "content marketers", postingTip: "Include distribution plan and evidence of content-market fit.", description: "r/content_marketing wants distribution, not just creation. 'We wrote a blog' without distribution is removed.", pitfalls: ["No blog link dump without distribution", "No low-effort 'content is king'", "No tool spam"], checklist: ["ICP, channel, and distribution steps listed", "Metrics: views, dwell, conversion included", "Repurposing workflow explained"] },
    { slug: "SEO", audience: "SEO practitioners", postingTip: "Back claims with examples, SERP context, and methodology.", description: "r/SEO expects URL, SERP, and methodology. 'How to rank?' without site detail is removed.", pitfalls: ["No low-effort ranking help without URL", "No affiliate or tool spam", "No unverified leak claims"], checklist: ["URL, keyword, SERP screenshot context included", "Methodology and timeline stated", "Tool stack and data source named"] },
    { slug: "ecommerce", audience: "ecommerce operators", postingTip: "Share channel, offer, and conversion context before asking for feedback.", description: "r/ecommerce needs platform, AOV, and traffic source. Store reviews without metrics are removed.", pitfalls: ["No store review without metrics", "No dropshipping spam", "No low-effort 'is my store good?'"], checklist: ["Platform, AOV, conversion rate, traffic source listed", "Product type and price point noted", "One specific bottleneck named"] },
];
